# Exercise Set 1

In [12]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

## Exercise 1

### View the first five rows of the DataFrame.

In [13]:
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

## Exercise 2
### View the last five rows of the DataFrame.

In [14]:
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

## Exercise 3
### Get basic info about the DataFrame.

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

## Exercise 4
### Check the shape of the DataFrame.

In [16]:
df.shape

(20, 4)

# Exercise Set 2

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head())

## Exercise 1
### Use .loc to get the name and age of the passenger with index 12.